export const LOADING_USERS = 'LOADING_USERS';
export const LOADED_USERS = 'LOADED_USERS';
export const LOADING_USERS_ERROR = 'LOADING_USERS_ERROR';

export const LOADING_USER = 'LOADING_USER';
export const LOADED_USER = 'LOADED_USER';
export const LOADING_USER_ERROR = 'LOADING_USERS_ERROR';

export const ADD_USER = 'ADD_USER';
export const ADDING_USER = 'ADDING_USER';
export const ADDING_USER_ERROR = 'ADDING_USER_ERROR';

export const DELETE_USER = 'DELETE_USER';
export const DELETING_USER = 'DELETING_USER';
export const DELETING_USER_ERROR = 'DELETING_USER_ERROR';

export const UPDATE_USER = 'UPDATE_USER';
export const UPDATING_USER = 'UPDATING_USER';
export const UPDATING_USER_ERROR = 'UPDATING_USER_ERROR';

export const AUTHENTICATING = 'AUTHENTICATING';
export const AUTHENTICATED = 'AUTHENTICATED';
export const AUTHENTICATION_ERROR = 'AUTHENTICATION_ERROR';

export const LOGGED_OUT = 'LOGGED_OUT';

export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_CONNECTING = 'SOCKET_CONNECTING';
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';
export const SOCKET_DISCONNECT = 'SOCKET_DISCONNECT';
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED';
export const SOCKET_ERROR= 'SOCKET_ERROR';
